<a href="https://colab.research.google.com/github/majorquev/DBDC_202409_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [1]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A



[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [2]:
B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [3]:
# clase y atributo dim
class(A)

[1] "matrix" "array"

In [4]:
dim(A)

[1] 2 3

In [6]:
# Genere dos vectores del mismo largo y forme una matriz.
c1 <- 1:4
c2 <- 10:13
c1
c2



[1] 1 2 3 4

[1] 10 11 12 13

In [8]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind
M1 <- cbind(c1,c2)
M1

c1 c2
[1,] 1  10
[2,] 2  11
[3,] 3  12
[4,] 4  13

In [9]:
M2 <- rbind(c1,c2)
M2

[,1] [,2] [,3] [,4]
c1  1    2    3    4  
c2 10   11   12   13

In [11]:
colnames(M1)
rownames(M1)

[1] "c1" "c2"

NULL

In [12]:
colnames(M2)
rownames(M2)

NULL

[1] "c1" "c2"

In [ ]:
# NOTA: Podemos añadir una fila/columna a una matriz existente


In [14]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
c3 <- c(-1:-4)
c3


[1] -1 -2 -3 -4

In [18]:
# Añadiremos c3 como nueva columna a M1
M1 <- cbind(M1,c3)
M1

c1 c2 c3
[1,] 1  10 -1
[2,] 2  11 -2
[3,] 3  12 -3
[4,] 4  13 -4

In [16]:
# función diag para la definición de matrices diagonales
#?diag

diag(c(1,4,6))


[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    4    0   
[3,] 0    0    6

In [22]:
M1

c1 c2 c3
[1,] 1  10 -1
[2,] 2  11 -2
[3,] 3  12 -3
[4,] 4  13 -4

In [20]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo: el "-2" de la posición (2,3)
M1[2,3]


c3 
-2

In [23]:
# CUIDADO:No es lo mismo que
M1[c(8,10)]

[1] 13 -2

In [25]:
# Para acceder a una fila completa
# Fila 3
M1[3,]

# Para acceder a una columna completa
# Columna 2
M1[,2]


c1 c2 c3 
 3 12 -3

[1] 10 11 12 13

In [26]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el -2 por un -99 (el -2 de la pos 2,3)
M1[2,3] <- -99
M1


c1 c2 c3 
[1,] 1  10  -1
[2,] 2  11 -99
[3,] 3  12  -3
[4,] 4  13  -4

In [27]:
# Acceso mediante nombres
M1

c1 c2 c3 
[1,] 1  10  -1
[2,] 2  11 -99
[3,] 3  12  -3
[4,] 4  13  -4

In [29]:
rownames(M1) <- paste("f",1:4,sep = "_")

In [30]:
M1

c1 c2 c3 
f_1 1  10  -1
f_2 2  11 -99
f_3 3  12  -3
f_4 4  13  -4

In [32]:
# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (2,3)

M1["f_2","c3"]

[1] -99

In [34]:
M1["f_2",]
M1[,"c3"]

c1  c2  c3 
  2  11 -99

f_1 f_2 f_3 f_4 
 -1 -99  -3  -4

In [40]:
# Acceso mediante "indicatrices" lógicas
# Quiero obtener los elementos (1,1) y (2,3) de M3
# 1: Crear una matriz de 4x3 con TRUE en dichas posiciones y FALSE en las restantes.
#rep(x = F, times = 12)
ind <- matrix(rep(F,12), ncol = 3, nrow = 4)
ind[1,1] <- T
ind[2,3] <- T
ind


[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE

In [42]:
M1

c1 c2 c3 
f_1 1  10  -1
f_2 2  11 -99
f_3 3  12  -3
f_4 4  13  -4

In [41]:
M1[ind]

[1]   1 -99

In [44]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M1[M1 >= 12]

[1] 12 13

In [47]:
M1[M1[,3] <= -4,3]

f_2 f_4 
-99  -4

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz
# t()

In [48]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices
M1 + M1


c1 c2 c3  
f_1 2  20   -2
f_2 4  22 -198
f_3 6  24   -6
f_4 8  26   -8

In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente


In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve
