<a href="https://colab.research.google.com/github/majorquev/DBDC_202409_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [4]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
 l1 <- list(num = 10:15,
            letra = c("x","y","z"),
            pl = "palabra",
            mat = diag(1:3),
            subl = list(a = c(T,T,F), fecha = as.Date("2024-09-24")))

In [5]:
l1

$num
[1] 10 11 12 13 14 15

$letra
[1] "x" "y" "z"

$pl
[1] "palabra"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$subl
$subl$a
[1]  TRUE  TRUE FALSE

$subl$fecha
[1] "2024-09-24"

In [6]:
length(l1)

[1] 5

In [7]:
# estructura
str(l1)

List of 5
 $ num  : int [1:6] 10 11 12 13 14 15
 $ letra: chr [1:3] "x" "y" "z"
 $ pl   : chr "palabra"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"


In [9]:
# Podemos guardar los objetos en slots sin nombres (no se los recomiendo en general)
list(1,"ha",diag(1:2))

[[1]]
[1] 1

[[2]]
[1] "ha"

[[3]]
     [,1] [,2]
[1,]    1    0
[2,]    0    2

In [11]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [14]:
# Podemos combinar listas
l2 <- list(v1 = LETTERS,
           num2 = 45.7)

str(l2)

l3 <- c(l1,l2)

List of 2
 $ v1  : chr [1:26] "A" "B" "C" "D" ...
 $ num2: num 45.7


In [15]:
str(l3)

List of 7
 $ num  : int [1:6] 10 11 12 13 14 15
 $ letra: chr [1:3] "x" "y" "z"
 $ pl   : chr "palabra"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"
 $ v1   : chr [1:26] "A" "B" "C" "D" ...
 $ num2 : num 45.7


In [18]:
# Acceso mediante posición
v <- l3[2]
v

$letra
[1] "x" "y" "z"

In [23]:
l3[c(2,4)]

$letra
[1] "x" "y" "z"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [26]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[2]# es una lista con el vector c(x,y,z)



$letra
[1] "x" "y" "z"

In [27]:
l3[[2]] # Es el vector x,y,z

[1] "x" "y" "z"

In [30]:
class(l3)
class(l3[2])
class(l3[[2]]) # Este es efectivamente el vector

[1] "list"

[1] "list"

[1] "character"

In [32]:
# El tercer elmento del vector que está en la pos 2 de la lista l3
l3[[2]][3]

[1] "z"

In [33]:
# de la lista l3[[5]], quieo el elemtno que está en el slot llamado "fecha" (segundo elemento)
str(l3)

List of 7
 $ num  : int [1:6] 10 11 12 13 14 15
 $ letra: chr [1:3] "x" "y" "z"
 $ pl   : chr "palabra"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"
 $ v1   : chr [1:26] "A" "B" "C" "D" ...
 $ num2 : num 45.7


In [35]:
l3[[5]] # Este si es el 5to elemento (que  a s vez es una lista)


$a
[1]  TRUE  TRUE FALSE

$fecha
[1] "2024-09-24"

In [37]:
l3[[5]][[2]]


[1] "2024-09-24"

In [38]:
str(l3)

List of 7
 $ num  : int [1:6] 10 11 12 13 14 15
 $ letra: chr [1:3] "x" "y" "z"
 $ pl   : chr "palabra"
 $ mat  : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"
 $ v1   : chr [1:26] "A" "B" "C" "D" ...
 $ num2 : num 45.7


In [40]:
# Acceso mediante nombre
# Tercer elemento del vector de la pos 2
l3[["letra"]][3]


[1] "z"

In [42]:
# de la lista subl, quiero el elemento que está en el slot llamado "fecha" (segundo elemento)
l3[["subl"]][["fecha"]]

[1] "2024-09-24"

In [44]:
# acceso vía "$"
l3$letra
l3[["letra"]] # es equivalente
l3[[2]] # es equivalente




[1] "x" "y" "z"

[1] "x" "y" "z"

[1] "x" "y" "z"

In [46]:
l3$letra[3]
l3$subl$fecha

[1] "z"

[1] "2024-09-24"

In [ ]:
# Nota:


In [49]:
# para saber el largo de la lista/vector
length(l3)
# Para obtener los nombres de la lista
names(l3)
# si quisiéramos renombrar los slots:
names(l3)[7] <- "numero_2"

[1] 7

[1] "num"   "letra" "pl"    "mat"   "subl"  "v1"    "num2"

In [50]:
str(l3)

List of 7
 $ num     : int [1:6] 10 11 12 13 14 15
 $ letra   : chr [1:3] "x" "y" "z"
 $ pl      : chr "palabra"
 $ mat     : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl    :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"
 $ v1      : chr [1:26] "A" "B" "C" "D" ...
 $ numero_2: num 45.7


In [52]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l3[["nuevo"]] <- letters

In [55]:
l3$nuevo2 <- "HOLA"

In [56]:
str(l3)

List of 9
 $ num     : int [1:6] 10 11 12 13 14 15
 $ letra   : chr [1:3] "x" "y" "z"
 $ pl      : chr "palabra"
 $ mat     : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ subl    :List of 2
  ..$ a    : logi [1:3] TRUE TRUE FALSE
  ..$ fecha: Date[1:1], format: "2024-09-24"
 $ v1      : chr [1:26] "A" "B" "C" "D" ...
 $ numero_2: num 45.7
 $ nuevo   : chr [1:26] "a" "b" "c" "d" ...
 $ nuevo2  : chr "HOLA"


In [58]:
# podemos modificar elementos dentro de un slot
# cambiar la fecha del ejemplo de mas arriba

l3$subl$fecha <- as.Date("2024-09-25")


In [59]:
l3$subl$fecha

[1] "2024-09-25"

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [60]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
df <- data.frame(edad = c(10,20,40),
                 rut = c("1-a", "4-b", "5-a"),
                 nombre = c("Miguel", "Macarena", "Milton") )


In [61]:
df

edad rut nombre  
1 10   1-a Miguel  
2 20   4-b Macarena
3 40   5-a Milton

In [62]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df[2]


rut
1 1-a
2 4-b
3 5-a

In [66]:
df[[2]]
df[["rut"]]
df$rut
df[,2] #  Ganamos acceso como matriz
df[,"rut"] #  Ganamos acceso como matriz

[1] "1-a" "4-b" "5-a"

[1] "1-a" "4-b" "5-a"

[1] "1-a" "4-b" "5-a"

[1] "1-a" "4-b" "5-a"

[1] "1-a" "4-b" "5-a"

In [69]:
##  Ganamos acceso como matriz
# segundafila de df
df[2,]

# segunda columna y segunda fila
df[2,2]
df[2,"rut"]
df$rut[2]# acceder como si fuese lista



edad rut nombre  
2 20   4-b Macarena

[1] "4-b"

[1] "4-b"

[1] "4-b"

In [ ]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista


In [73]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3
df[,c(2,3)] # Pensando como matriz
df[c(2,3)]  # Pensando como lista
# Referenciando el nombre de las columnas
df[,c("rut","nombre")]# Pensando como matriz
df[c("rut","nombre")]# Pensando como lista

rut nombre  
1 1-a Miguel  
2 4-b Macarena
3 5-a Milton

rut nombre  
1 1-a Miguel  
2 4-b Macarena
3 5-a Milton

rut nombre  
1 1-a Miguel  
2 4-b Macarena
3 5-a Milton

rut nombre  
1 1-a Miguel  
2 4-b Macarena
3 5-a Milton

In [74]:
df

edad rut nombre  
1 10   1-a Miguel  
2 20   4-b Macarena
3 40   5-a Milton

In [77]:
df[df$edad > 15 ,]

edad rut nombre  
2 20   4-b Macarena
3 40   5-a Milton

In [76]:
df[df$edad > 15 & grepl("-b", df$rut) ,]

edad rut nombre  
2 20   4-b Macarena